chime9_dir: data/chime9_echi
scratch_dir: data/scratch
minitest_dir: data/minitests/mini_test_v2
transcript_dir: data/perfect_transcripts

sessions_file: ${paths.chime9_dir}/metadata/sessions.{dataset}.csv

raw_transcript_file: ${paths.transcript_dir}/raw/{dataset}/{session}.ct_{pos}.json
tidy_transcript_file: ${paths.transcript_dir}/tidy/{dataset}/{session}.transcript.{pid}.json

rainbow_file: ${paths.chime9_dir}/participant/{dataset}/{pid}.wav
noisy_session_file: ${paths.chime9_dir}/{device}/{dataset}/{session}.{device}.wav
ref_session_file: ${paths.chime9_dir}/ref/{dataset}/{session}.{device}.{pid}.wav
ct_session_file: ${paths.chime9_dir}/ct/{dataset}/{session}.ct_{pid}.wav
segments_file: ${paths.chime9_dir}/metadata/ref/{dataset}/{session}.{device}.{pid}.csv

noisy_seg_file: ${paths.scratch_dir}/{device}/{dataset}/{session}.{device}.{pid}.{seg}.{start}_{end}.wav
ref_seg_file: ${paths.scratch_dir}/ref/{dataset}/{session}.{device}_ref.{pid}.{seg}.{start}_{end}.wav

filtered_dir: ${paths.minitest_dir}/{system}
filtered_file: ${paths.filtered_dir}/{session}.{device}.{pid}.{seg}.{start}_{end}.wav
filtered_store: ${paths.minitest_dir}/segments.json
tsv_dir: ${paths.minitest_dir}/tsv
representation_dir: ${paths.scratch_dir}/{representation}/{dataset}
representation_file: ${paths.representation_dir}/{session}.{device}.{pid}.{seg}.{start}_{end}.pt

exp_session_file: ${paths.scratch_dir}/{exp}/{session}.{device}.{pid}.wav
exp_segment_video: ${paths.minitest_dir}/{exp}/{session}.{device}.{pid}.{seg}.{anim}.mp4
exp_segment_audio: ${paths.minitest_dir}/{exp}/{session}.{device}.{pid}.{seg}.wav

animations_file: ${paths.minitest_dir}/animations/{session}.{device}.{pid}.{seg}.{anim}.mp4
test_rainbow_file: ${paths.minitest_dir}/rainbow/{pid}.wav