defaults:
  - .@paths: paths
  - _self_

dataset: test
rng_seed: 666

sessions_file: ${paths.sessions_file}

transcript_file: ${paths.tidy_transcript_file}
testable_file: ${paths.testable_transcript_file}

min_words: 5
max_words: 9

prewindow: 5 # time before utterance to check, in seconds